/*
 * AUTOGENERATED - DON'T EDIT
 * Your edits in this file will be overwritten in the next build!
 * Modify the docusaurus.config.js file at your site's root instead.
 */
export default {
  "title": "Chess Endgames",
  "tagline": "Master the art of converting advantages into victories",
  "favicon": "img/favicon.ico",
  "url": "https://melvincarvalho.github.io",
  "baseUrl": "/endgames/",
  "organizationName": "melvincarvalho",
  "projectName": "endgames",
  "trailingSlash": false,
  "deploymentBranch": "gh-pages",
  "onBrokenLinks": "warn",
  "future": {
    "v4": {
      "removeLegacyPostBuildHeadAttribute": true,
      "useCssCascadeLayers": true
    },
    "experimental_faster": {
      "swcJsLoader": false,
      "swcJsMinimizer": false,
      "swcHtmlMinimizer": false,
      "lightningCssMinimizer": false,
      "mdxCrossCompilerCache": false,
      "rspackBundler": false,
      "rspackPersistentCache": false,
      "ssgWorkerThreads": false
    },
    "experimental_storage": {
      "type": "localStorage",
      "namespace": false
    },
    "experimental_router": "browser"
  },
  "i18n": {
    "defaultLocale": "en",
    "locales": [
      "en"
    ],
    "path": "i18n",
    "localeConfigs": {}
  },
  "presets": [
    [
      "classic",
      {
        "docs": {
          "sidebarPath": "./sidebars.ts",
          "routeBasePath": "/",
          "editUrl": "https://github.com/melvincarvalho/endgames/tree/main/"
        },
        "blog": false,
        "theme": {
          "customCss": "./src/css/custom.css"
        }
      }
    ]
  ],
  "themeConfig": {
    "image": "img/social-card.png",
    "metadata": [
      {
        "name": "keywords",
        "content": "chess, endgames, endgame study, chess training, Lucena, Philidor, opposition"
      },
      {
        "name": "description",
        "content": "Comprehensive chess endgame documentation with themes and difficulty levels"
      },
      {
        "property": "og:type",
        "content": "website"
      }
    ],
    "colorMode": {
      "defaultMode": "light",
      "disableSwitch": false,
      "respectPrefersColorScheme": true
    },
    "navbar": {
      "title": "Chess Endgames",
      "logo": {
        "alt": "Chess Endgames Logo",
        "src": "img/logo.svg"
      },
      "items": [
        {
          "to": "/study-paths/overview",
          "label": "Study Paths",
          "position": "left"
        },
        {
          "to": "/fundamentals/basic-checkmates/overview",
          "label": "Fundamentals",
          "position": "left"
        },
        {
          "type": "dropdown",
          "label": "By Material",
          "position": "left",
          "items": [
            {
              "label": "Pawn Endgames",
              "to": "/pawn-endgames/principles"
            },
            {
              "label": "Rook Endgames",
              "to": "/rook-endgames/principles"
            },
            {
              "label": "Minor Pieces",
              "to": "/minor-piece-endgames/overview"
            },
            {
              "label": "Queen Endgames",
              "to": "/queen-endgames/overview"
            }
          ]
        },
        {
          "to": "/strategic-themes/overview",
          "label": "Themes",
          "position": "left"
        },
        {
          "href": "https://github.com/melvincarvalho/endgames",
          "label": "GitHub",
          "position": "right"
        }
      ],
      "hideOnScroll": false
    },
    "footer": {
      "style": "dark",
      "links": [
        {
          "title": "Study",
          "items": [
            {
              "label": "Getting Started",
              "to": "/getting-started/introduction"
            },
            {
              "label": "Study Paths",
              "to": "/study-paths/overview"
            },
            {
              "label": "Fundamentals",
              "to": "/fundamentals/basic-checkmates/overview"
            }
          ]
        },
        {
          "title": "By Material",
          "items": [
            {
              "label": "Pawn Endgames",
              "to": "/pawn-endgames/principles"
            },
            {
              "label": "Rook Endgames",
              "to": "/rook-endgames/principles"
            },
            {
              "label": "Minor Pieces",
              "to": "/minor-piece-endgames/overview"
            }
          ]
        },
        {
          "title": "Resources",
          "items": [
            {
              "label": "Glossary",
              "to": "/reference/glossary"
            },
            {
              "label": "Book Recommendations",
              "to": "/reference/books"
            },
            {
              "label": "GitHub",
              "href": "https://github.com/melvincarvalho/endgames"
            }
          ]
        }
      ],
      "copyright": "Copyright © 2026 Chess Endgames. Built with Docusaurus."
    },
    "prism": {
      "theme": {
        "plain": {
          "color": "#393A34",
          "backgroundColor": "#f6f8fa"
        },
        "styles": [
          {
            "types": [
              "comment",
              "prolog",
              "doctype",
              "cdata"
            ],
            "style": {
              "color": "#999988",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "namespace"
            ],
            "style": {
              "opacity": 0.7
            }
          },
          {
            "types": [
              "string",
              "attr-value"
            ],
            "style": {
              "color": "#e3116c"
            }
          },
          {
            "types": [
              "punctuation",
              "operator"
            ],
            "style": {
              "color": "#393A34"
            }
          },
          {
            "types": [
              "entity",
              "url",
              "symbol",
              "number",
              "boolean",
              "variable",
              "constant",
              "property",
              "regex",
              "inserted"
            ],
            "style": {
              "color": "#36acaa"
            }
          },
          {
            "types": [
              "atrule",
              "keyword",
              "attr-name",
              "selector"
            ],
            "style": {
              "color": "#00a4db"
            }
          },
          {
            "types": [
              "function",
              "deleted",
              "tag"
            ],
            "style": {
              "color": "#d73a49"
            }
          },
          {
            "types": [
              "function-variable"
            ],
            "style": {
              "color": "#6f42c1"
            }
          },
          {
            "types": [
              "tag",
              "selector",
              "keyword"
            ],
            "style": {
              "color": "#00009f"
            }
          }
        ]
      },
      "darkTheme": {
        "plain": {
          "color": "#F8F8F2",
          "backgroundColor": "#282A36"
        },
        "styles": [
          {
            "types": [
              "prolog",
              "constant",
              "builtin"
            ],
            "style": {
              "color": "rgb(189, 147, 249)"
            }
          },
          {
            "types": [
              "inserted",
              "function"
            ],
            "style": {
              "color": "rgb(80, 250, 123)"
            }
          },
          {
            "types": [
              "deleted"
            ],
            "style": {
              "color": "rgb(255, 85, 85)"
            }
          },
          {
            "types": [
              "changed"
            ],
            "style": {
              "color": "rgb(255, 184, 108)"
            }
          },
          {
            "types": [
              "punctuation",
              "symbol"
            ],
            "style": {
              "color": "rgb(248, 248, 242)"
            }
          },
          {
            "types": [
              "string",
              "char",
              "tag",
              "selector"
            ],
            "style": {
              "color": "rgb(255, 121, 198)"
            }
          },
          {
            "types": [
              "keyword",
              "variable"
            ],
            "style": {
              "color": "rgb(189, 147, 249)",
              "fontStyle": "italic"
            }
          },
          {
            "types": [
              "comment"
            ],
            "style": {
              "color": "rgb(98, 114, 164)"
            }
          },
          {
            "types": [
              "attr-name"
            ],
            "style": {
              "color": "rgb(241, 250, 140)"
            }
          }
        ]
      },
      "additionalLanguages": [],
      "magicComments": [
        {
          "className": "theme-code-block-highlighted-line",
          "line": "highlight-next-line",
          "block": {
            "start": "highlight-start",
            "end": "highlight-end"
          }
        }
      ]
    },
    "tableOfContents": {
      "minHeadingLevel": 2,
      "maxHeadingLevel": 4
    },
    "docs": {
      "versionPersistence": "localStorage",
      "sidebar": {
        "hideable": false,
        "autoCollapseCategories": false
      }
    },
    "blog": {
      "sidebar": {
        "groupByYear": true
      }
    }
  },
  "baseUrlIssueBanner": true,
  "onBrokenAnchors": "warn",
  "onDuplicateRoutes": "warn",
  "staticDirectories": [
    "static"
  ],
  "customFields": {},
  "plugins": [],
  "themes": [],
  "scripts": [],
  "headTags": [],
  "stylesheets": [],
  "clientModules": [],
  "titleDelimiter": "|",
  "noIndex": false,
  "markdown": {
    "format": "mdx",
    "mermaid": false,
    "emoji": true,
    "mdx1Compat": {
      "comments": true,
      "admonitions": true,
      "headingIds": true
    },
    "anchors": {
      "maintainCase": false
    },
    "hooks": {
      "onBrokenMarkdownLinks": "warn",
      "onBrokenMarkdownImages": "throw"
    }
  }
};
